oslokommune/ukeweb_designsystem

- src/components/header/header.html
- src/components/icon/icon.html
- src/components/image/image.html
- src/components/image_carousel/image_carousel.html
- src/components/infobox/infobox.html
- src/components/links/link/link.html
- src/components/links/service_link/service_link.html
- src/components/list/list.html
- src/components/logo/logo.html
- src/components/map/map.html
- src/components/menu/menu.html
- src/components/message/message.html
- src/components/modal/modal.html
- src/components/opening_hours/opening_hours.html
- src/components/pagination/pagination.html
- src/components/paragraph/paragraph.html
- src/components/service_header/service_header.html
- src/components/status_indicators/loading/loading.html
- src/components/status_message/status_message.html
- src/components/step_by_step/step_by_step.html
- src/components/table/table.html
- src/components/toc/toc.html
- src/components/video/video.html
Changed components to use the new osg-grid
> Changecomponentstousethenewgri

- src/components/tabs/tabs.html
- src/components/tabs/tabs.js
- src/components/tabs/tabs.scss
PR is partial because of earlier commits to main branch - before Trello.
Based on https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-manual.html.
> Tabs component - 1st edition

- src/components/map/map.scss
- src/components/map/map.vue
- src/general/_index.scss
- src/general/helpers/ratio/ratio.html
- src/general/helpers/ratio/ratio.json
- src/general/helpers/ratio/ratio.scss
> Added ratio to helpers and removed fixed height on map component

- src/components/toc/toc.html
- src/components/toc/toc.scss
Fikk det ikke til å fly med ::before derfor ble det span
> toc adjust icon size

- package.json
- src/components/_index.js
- src/components/contact/contactbox/contactbox.html
- src/components/contact/contactbox/contactbox.init.js
- src/components/contact/contactbox/contactbox.js
- src/components/contact/contactbox/contactbox.scss
- src/components/links/service_link/service_link.scss
- contactbox collaps
- 0.99.77
- adjusts line height for icon
> io-313 icon adjustsments service link

- src/components/contact/contactpoint/contactpoint.scss
https://www.figma.com/file/SXRIvAofDrr3VBDqLdPHVu/Konaktboks
> changes to font and spacing in contactpoint component

- package.json
- src/common/_global.scss
- 0.99.80
- adds the text-size-adjust property
> io-326 sets text-size-adjust to none

- src/components/form/search_seasons/search_seasons.scss
> fixed overriding styling on iphone for search seasons

- package.json
- src/components/alert/alert.json
- src/components/alert/alert.scss
- src/components/links/personalized_content_link/personalized_content_link.json
- src/components/links/personalized_content_link/personalized_content_link.scss
- src/components/message/message.json
- src/components/message/message.scss
- src/general/grid/grid.scss
- src/general/helpers/spacing/spacing.html
- src/general/helpers/spacing/spacing.init.js
- src/system/_spacing.scss
- 0.99.81
- adds width 100% to columns
- 0.99.82
- new spacing 6, set spacing 6 bp large 3 comps
> io-409 new spacing 6, set space 6 bp large 3 comps

- src/components/header/header.html
- src/components/header/header.scss
- src/components/menu/menu.html
- src/components/menu/menu.scss
Dette inkluderer også:
- Legge til horisontal padding i meny knappen og underline i hover state
- Legge til ikoner til søk boks i header
- Viser meny knappen i medium breakpoint
> Io 527 - Flere fikser i header for ikke å viser overlappet 

- package.json
- src/components/image_carousel/image_carousel.html
- src/components/image_carousel/image_carousel.vue
- src/components/menu/menu.scss
- src/general/colors/palette/palette.html
- src/system/_colors.scss
!!! My commit contains changes from _colors.scss and palette.html
> Fixed grayscale

- src/components/form/search_seasons/search_seasons.html
- src/components/form/search_seasons/search_seasons.js
- src/components/form/search_seasons/search_seasons.vue
Legg til en slot for man har muligheten til å bestemme hvilken overskrift som skal ha.
> Change search seasons heading

- src/components/form/switch/switch.scss
Til diskusjon: Rem på border???
> io-124 used rem not px

- src/components/cards/landscape_card/landscape_card.html
- src/components/cards/landscape_card/landscape_card.scss
Oppdatert cards, regler for textbegrensninger settes i prosjekt
figma: https://www.figma.com/file/vCTk2OSXeQH0MmwszqNvF3/Cards?node-id=0%3A1&t=xayZWa4PMc6evaFe-0
> io-697 card with blue background

- src/components/collapsible/collapsible.js
- src/components/infobox/infobox.html
- src/components/infobox/infobox.scss
Figma:
https://www.figma.com/file/rxoZxn1NkFjhyWIqGp4cS8/Faktaboks?node-id=2%3A169&t=XykHdR1uSp1y89HK-0
> Added infobox collapsible variant

- src/components/cards/landscape_card/landscape_card.html
la til en sluttdiv som manglet, fjernet også flexbox på to cards som var på "developerfanen" og noe lorem ipsum tekst (så det ser litt bedre ut om man resizer)
> added missing closing div and removed display flex on two cards

- src/components/cards/landscape_card/landscape_card.scss
> Io 697 - align text in card

- package.json
- src/components/form/fieldset/fieldset.html
- src/components/form/search/search.scss
changed spacing on fieldset - collapsible content
> Io 706 - changed spacing on fieldset

- src/components/links/link/link.html
- src/components/links/link/link.scss
> Adds no decoration modifier to links.

- src/components/form/search/circle/circle.html
- src/components/form/search/circle/circle.scss
- src/components/form/search_seasons/search_seasons.html
- src/components/form/search_seasons/search_seasons.scss
- Fix palete text size for blue state
- Wrap texts in contactbox with html semantics
- Refactors markup of circle and seasons to be compliant with wcag giving a better experience for screen readers
> io-878 Refactors markup for circle and seasons to be compliant with wcag giving a better experience for screen readers

- CHANGELOG.md
- src/components/cards/portrait_card/portrait_card.scss
test ok fra stine (endringene ligger mao i test om man vil se)
> Io 857 - fixed font weight on xs card

- src/components/alert/alert.html
Ser ut som trello-kortet var litt utdatert, men jeg endret setningene litt.
> Io 147 - update alert documentation

- CHANGELOG.md
- src/general/grid/grid.scss
Add breakpoint subclasses to grid gap
Remove placeholders for column and row in grid
> io-1091 Refactor grid so classes are generated properly

- CHANGELOG.md
- src/components/accordion/accordion.scss
Sånn, da er commits signet :( :) :( :)
> Io 1097 - fix border, padding and margin on accordion component 

- CHANGELOG.md
- src/components/service_header/service_header.scss
Ligger i test om man vil se over
> io-1117 removed column gap on service header

- CHANGELOG.md
- src/components/form/radio/radio.scss
- Endre bakgrunn farge for default state av radio button til dark-blue
- Legge til undertrek til label tekst
> io-1128 Change background color and text for default state of radio button

- CHANGELOG.md
- src/components/map/map.html
- src/components/map/map.js
- src/components/map/map.scss
- Oppdater geojson filer for å bruke .ods klasser.
- Oppdater styling basert på figma: 
- https://www.figma.com/file/5qGdzlm71izSTS86YhJQIo/ML---Maplibre?type=design&node-id=119-5340&mode=design&t=S96ae68lqdK71Bcn-0
> io-118 Change style for the popup in the map component

- CHANGELOG.md
- src/components/pagination/pagination.init.js
Small tweak to component registration to support our current syntax
> IO-1268: fix pagination component registration

- CHANGELOG.md
- src/components/video/video.scss
> io-1178: change video heading to correct font weight

- .gitignore
- .npmignore
- CHANGELOG.md
- src/osg.js
- src/osg.scss
https://trello.com/c/T5djUC24/1240-fix-npm-package-ting
- add config files to .gitignore
- remove old styleguide files
> io-1240 Fix npm warnings and remove remaining old styleguide files

- CHANGELOG.md
- src/components/button/button.scss
- src/components/cards/portrait_card/portrait_card.html
- src/components/cards/portrait_card/portrait_card.scss
Her har jeg lagt til en ny klasse som heter actions-clean som fjerner padding på alt som blir lagt som child i __actions delen av cardet.
> IO-426: Change padding in portrait cards and align custom content

- .eslintrc.json
- src/components/form/search/inline/inline.vue
- src/components/image_carousel/image_carousel.vue
https://eslint.vuejs.org/rules/
Oppdaterer vue-essentials til vue3 variant og fikser påfølgende linting errors laget av vue3 varianten.
> IO-1305: Update vue-essentials plugin

- CHANGELOG.md
- src/components/banner/banner.html
- src/components/banner/banner.scss
https://trello.com/c/66446203fc8d5ee02125a7fc
> io-1310: Update sizes of links, headings and paragrafs in banner

- src/components/menu/menu.scss
https://trello.com/c/kyOPl263/1309-menu-feil-heading-p%C3%A5-m-brekkpunkt
> io-1309: Fix size of heading in menu to India on breakpoint medium

- src/components/form/checkbox/checkbox.html
- src/components/form/radio/radio.html
https://trello.com/c/myLrVTmd/1315-plassering-av-error-required
> io-1315: Moved the 'required' text under the error message for checkbox and radio button

- CHANGELOG.md
- src/components/map/map.html
- src/general/helpers/code/code.html
- src/general/helpers/collapsible/collapsible.html
- src/getting_started/consume/packages/packages.html
- src/getting_started/contribute/basics/basics.html
Gjerne tilbakemelding her!
Litt usikker på om jeg linker til riktig vue side? Skal vi linke til noe mere spesifikt?
Ser dokumentasjonen bra ut?
> IO-1321: Update documentation
